In [76]:
import pandas as pd
import numpy as nb
import matplotlib as plt

In [77]:
df = pd.read_csv("players_15.csv")

In [78]:
df.head(2)

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,27,1987-06-24,169,67,Argentina,FC Barcelona,...,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,29,1985-02-05,185,80,Portugal,Real Madrid,...,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3

In [79]:
df.tail(2)

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
16153,222947,https://sofifa.com/player/222947/tom-davies/15...,T. Davies,Tom Davies,22,1992-04-18,180,70,England,Fleetwood Town,...,37+0,36+0,36+0,36+0,37+0,39+0,40+0,40+0,40+0,39+0
16154,201197,https://sofifa.com/player/201197/paul-tisdale/...,P. Tisdale,Paul Tisdale,41,1973-01-14,175,72,Malta,Exeter City,...,36+0,37+0,37+0,37+0,36+0,34+0,33+0,33+0,33+0,34+0

In [80]:
df.shape

(16155, 106)

In [81]:
df.columns

Index(['sofifa_id', 'player_url', 'short_name', 'long_name', 'age', 'dob',
       'height_cm', 'weight_kg', 'nationality', 'club_name',
       ...
       'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb'],
      dtype='object', length=106)

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16155 entries, 0 to 16154
Columns: 106 entries, sofifa_id to rb
dtypes: float64(18), int64(44), object(44)
memory usage: 13.1+ MB

In [83]:
df.describe()

,sofifa_id,age,height_cm,weight_kg,league_rank,overall,potential,value_eur,wage_eur,international_reputation,...,mentality_penalties,mentality_composure,defending_marking,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
count,16155.000000,16155.000000,16155.000000,16155.000000,15916.000000,16155.000000,16155.000000,1.615500e+04,16155.000000,16155.000000,...,16155.000000,0.0,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000
mean,189284.184525,24.776230,181.083627,75.474342,1.378424,63.830393,68.350108,1.060882e+06,13056.453110,1.122501,...,49.648344,NaN,45.009037,47.656639,45.885918,15.869514,15.511668,15.354875,15.504735,15.998514
std,39749.261554,4.625321,6.618974,6.891796,0.736796,7.169896,6.580610,2.819128e+06,23488.182571,0.396263,...,14.552244,NaN,17.915206,18.743105,18.145497,17.576799,16.414173,16.010498,16.585081,17.983209
min,2.000000,16.000000,155.000000,50.000000,1.000000,40.000000,40.000000,0.000000e+00,0.000000,1.000000,...,20.000000,NaN,20.000000,20.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,178042.500000,21.000000,176.000000,70.000000,1.000000,59.000000,64.000000,1.200000e+05,2000.000000,1.000000,...,39.000000,NaN,25.000000,25.000000,25.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,200841.000000,24.000000,181.000000,75.000000,1.000000,64.000000,68.000000,3.500000e+05,5000.000000,1.000000,...,50.000000,NaN,46.000000,52.000000,49.000000,11.000000,11.000000,11.000000,10.000000,10.000000
75%,214346.000000,28.000000,186.000000,80.000000,2.000000,68.000000,73.000000,8.250000e+05,10000.000000,1.000000,...,61.000000,NaN,61.000000,64.000000,62.000000,13.000000,14.000000,13.000000,13.000000,13.000000
max,225562.000000,44.000000,204.000000,110.000000,4.000000,93.000000,95.000000,1.005000e+08,550000.000000,5.000000,...,95.000000,NaN,90.000000,91.000000,95.000000,88.000000,87.000000,92.000000,90.000000,90.000000

In [84]:
df.dtypes

sofifa_id      int64
player_url    object
short_name    object
long_name     object
age            int64
               ...
lb            object
lcb           object
cb            object
rcb           object
rb            object
Length: 106, dtype: object

In [85]:
df["height_cm"]

0        169
1        185
2        180
3        195
4        193
        ...
16150    187
16151    178
16152    190
16153    180
16154    175
Name: height_cm, Length: 16155, dtype: int64

In [86]:
mean = df["height_cm"].mean()

In [87]:
#Standard deviation
sd = df["height_cm"].std()

In [88]:
# How many people are above 183
# Z = (x - Mew)/sigma
# (185 - mean) / sd

tallerthan185 = (185 - mean) / sd

In [89]:
tallerthan185

np.float64(0.5916887429753471)

In [90]:
shorterthan173 = (175 - mean) / sd

In [91]:
shorterthan173

np.float64(-0.9191193372482548)

In [92]:
# Weight probability of pickiung someone whose weight is between 90 and 100

In [93]:
# Calculate mean
meanw = df["weight_kg"].mean()

In [94]:
# Calculate mean
sdw = df["weight_kg"].std()

In [95]:
# Calculate z for 90
above90 = (90 - meanw) / sdw

In [96]:
above90

np.float64(2.107673821629863)

In [97]:
# Calculate z for 90
below100 = (100 - meanw) / sdw

In [98]:
below100

np.float64(3.5586744347853987)

In [99]:
#table vale for .99981 table value for .98214

In [100]:
# Probability for pickiung someone whose weight is between 90 and 100
probw = (.99981 - .98214) * 100

In [101]:
probw

1.7669999999999964