In [21]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [22]:
df = pd.read_csv('E_Webdata.csv')

In [23]:
df

,# ----------------------------------------,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Session primary channel group (Default channel...,Date + hour (YYYYMMDDHH),Users,Sessions,Engaged sessions,Average engagement time per session,Engaged sessions per user,Events per session,Engagement rate,Event count
1,Direct,2024041623,237,300,144,47.526666666666700,0.6075949367088610,4.673333333333330,0.48,1402
2,Organic Social,2024041719,208,267,132,32.09737827715360,0.6346153846153850,4.295880149812730,0.4943820224719100,1147
3,Direct,2024041723,188,233,115,39.93991416309010,0.6117021276595740,4.587982832618030,0.49356223175965700,1069
4,Organic Social,2024041718,187,256,125,32.16015625,0.6684491978609630,4.078125,0.48828125,1044
...,...,...,...,...,...,...,...,...,...,...
3178,Unassigned,2024042806,0,1,0,0,0,2,0,2
3179,Unassigned,2024043005,0,1,0,0,0,2,0,2
3180,Unassigned,2024043006,0,1,0,0,0,2,0,2
3181,Unassigned,2024050105,0,1,0,0,0,2,0,2
3182,Unassigned,2024050307,0,1,0,0,0,2,0,2

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3183 entries, 0 to 3182
Data columns (total 10 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   # ----------------------------------------  3183 non-null   str
 1   Unnamed: 1                                  3183 non-null   str
 2   Unnamed: 2                                  3183 non-null   str
 3   Unnamed: 3                                  3183 non-null   str
 4   Unnamed: 4                                  3183 non-null   str
 5   Unnamed: 5                                  3183 non-null   str
 6   Unnamed: 6                                  3183 non-null   str
 7   Unnamed: 7                                  3183 non-null   str
 8   Unnamed: 8                                  3183 non-null   str
 9   Unnamed: 9                                  3183 non-null   str
dtypes: str(10)
memory usage: 248.8 KB

In [25]:
df.describe(include = 'all')

,# ----------------------------------------,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
count,3183,3183,3183,3183,3183,3183,3183,3183,3183,3183
unique,8,673,148,181,104,2824,809,2026,987,679
top,Direct,2024041719,1,1,0,0,0,1,0,1
freq,672,6,335,340,393,170,393,133,393,115

In [ ]:
df.columns = df.iloc[0]
# Make index 0 row as header

In [27]:
df.columns

Index(['Session primary channel group (Default channel group)',
       'Date + hour (YYYYMMDDHH)', 'Users', 'Sessions', 'Engaged sessions',
       'Average engagement time per session', 'Engaged sessions per user',
       'Events per session', 'Engagement rate', 'Event count'],
      dtype='str', name=0)

In [ ]:
df = df.drop(index = 0).reset_index(drop = True)
# Drop row on index 0

df.columns = ['channel group','Datehour', 'Users', 'Sessions', 'Engaged sessions','Average engagement time per session', 'Engaged sessions per user','Events per session', 'Engagement rate', 'Event count']
# Correct the name of columns in header