In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("deliveries.csv")

In [19]:
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [4]:
df.tail(5)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  str
 3   bowling_team      179078 non-null  str
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  str
 7   non_striker       179078 non-null  str
 8   bowler            179078 non-null  str
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    str
 19  dismissal_kind    8834 non-null    str
 20  fielder           6448 non-null    str
dtypes: int64(13), str(8)
memory usage: 28.7 MB

In [7]:
df.shape

(179078, 21)

In [12]:
!pip install scipy

Collecting scipy
  Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: numpy<2.8,>=2.0.0 in C:\Users\Shiva Thakur\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scipy) (2.5.1)
Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ---------- ----------------------------- 9.4/37.3 MB 53.9 MB/s eta 0:00:01
   ------------- -------------------------- 12.3/37.3 MB 29.8 MB/s eta 0:00:01
   -------------- ------------------------- 13.6/37.3 MB 23.0 MB/s eta 0:00:02
   --------------- ------------------------ 14.4/37.3 MB 16.9 MB/s eta 0:00:02
   ---------------- ----------------------- 15.2/37.3 MB 14.5 MB/s eta 0:00:02
   ----------------- ---------------------- 16.5/37.3 MB 13.0 MB/s eta 0:00:02
   ------------------- -------------------- 18.1/37.3 MB 12.3 MB/s eta 0:00:02
   --------------------- ------------------ 20.2/37.3 MB 11.9 MB/s eta 0:00:02
   ------------------------ --------------- 22.5/37.3 MB 11.9 MB/s eta 0:00:02
   -------------------------- ------------- 25.2/37.3 MB 12.0 MB/s eta 0:00:02
   ------------------------------ --------- 28.6/37.3 MB 12.3 MB/s eta 0:00:01
   ---------------------------------- ----- 32.5/37.3 MB 12.8 MB/s eta 0:00:01
   ---------------------------------------  36.4/37.3 MB 13.2 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 13.0 MB/s  0:00:02
Installing collected packages: scipy
Successfully installed scipy-1.18.0

In [14]:
harbhajan = df[df["bowler"] == "Harbhajan Singh"]
harbhajan.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
1478,7,1,Kolkata Knight Riders,Mumbai Indians,9,1,MK Pandey,YK Pathan,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1479,7,1,Kolkata Knight Riders,Mumbai Indians,9,2,MK Pandey,YK Pathan,Harbhajan Singh,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
1480,7,1,Kolkata Knight Riders,Mumbai Indians,9,3,YK Pathan,MK Pandey,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1481,7,1,Kolkata Knight Riders,Mumbai Indians,9,4,YK Pathan,MK Pandey,Harbhajan Singh,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
1482,7,1,Kolkata Knight Riders,Mumbai Indians,9,5,YK Pathan,MK Pandey,Harbhajan Singh,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN

In [22]:
totalruns = df[df["batsman"] == "V Kohli"]["total_runs"].sum()
totalruns

np.int64(5616)